/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.nhom25.btl_cnpm.view.pages;

import com.nhom25.btl_cnpm.controller.HouseholdController;
import com.nhom25.btl_cnpm.dao.ConnectionController;
import com.nhom25.btl_cnpm.entity.Household;
import com.nhom25.btl_cnpm.view.IndexView;
import java.awt.BorderLayout;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

import java.awt.Color;
import java.awt.Font;
import java.io.IOException;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.plaf.RootPaneUI;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author hungn
 */
public class HouseholdManageJP extends javax.swing.JPanel {

    /**
     * Creates new form HouseholdManageJP
     */
    
    DefaultTableModel model;
    List<Household> householdList = new ArrayList<>();
    
    public HouseholdManageJP(){
        try {
            initComponents();
            
            model = (DefaultTableModel) householdTable.getModel();
            ConnectionController con = new ConnectionController();
            householdList = con.findAllHousehold();
            showHousehold();
        } catch (SQLException ex) {
            Logger.getLogger(HouseholdManageJP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    public void showHousehold(){
        try {
            ConnectionController con = new ConnectionController();
            householdList = con.findAllHousehold();
            model.setRowCount(0);
            for(Household h : householdList){
                model.addRow(new Object[]{model.getRowCount() + 1, 
                    h.getHouseholder(), h.getNumOfPeople()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(HouseholdManageJP.class.getName()).log(Level.SEVERE, null, ex);
        }        
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        householdTable = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        txtName = new javax.swing.JTextField();
        addHouseHoldBtn = new javax.swing.JButton();
        deleteHouseHoldBtn = new javax.swing.JButton();
        seeHouseHoldBtn = new javax.swing.JButton();
        btnSearchHousehold = new javax.swing.JButton();
        btnChangeInfo = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        householdTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Tên chủ hộ", "Số người"
            }
        ));
        householdTable.setGridColor(new java.awt.Color(153, 153, 153));
        jScrollPane1.setViewportView(householdTable);

        jLabel1.setText("Tìm kiếm:");

        addHouseHoldBtn.setText("Thêm");
        addHouseHoldBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addHouseHoldBtnActionPerformed(evt);
            }
        });

        deleteHouseHoldBtn.setText("Xóa");
        deleteHouseHoldBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteHouseHoldBtnActionPerformed(evt);
            }
        });

        seeHouseHoldBtn.setText("Xem");
        seeHouseHoldBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seeHouseHoldBtnActionPerformed(evt);
            }
        });

        btnSearchHousehold.setText("Tìm");
        btnSearchHousehold.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchHouseholdActionPerformed(evt);
            }
        });

        btnChangeInfo.setText("Sửa");
        btnChangeInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChangeInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 881, Short.MAX_VALUE)))
                .addGap(44, 44, 44)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(deleteHouseHoldBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(seeHouseHoldBtn, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(btnSearchHousehold, javax.swing.GroupLayout.DEFAULT_SIZE, 65, Short.MAX_VALUE)
                    .addComponent(addHouseHoldBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChangeInfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearchHousehold))
                .addGap(89, 89, 89)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 453, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addComponent(addHouseHoldBtn)
                        .addGap(70, 70, 70)
                        .addComponent(seeHouseHoldBtn)
                        .addGap(65, 65, 65)
                        .addComponent(btnChangeInfo)
                        .addGap(83, 83, 83)
                        .addComponent(deleteHouseHoldBtn)
                        .addContainerGap())))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void deleteHouseHoldBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteHouseHoldBtnActionPerformed
        // TODO add your handling code here:
        int r = householdTable.getSelectedRow();
        if(r > -1){
            int input = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn xoá hộ dân này không?\nKhông thể hoàn lại thao tác này.", "Xác nhận", 0);
            if(input == 0){
                try {
                    HouseholdController hcon = new HouseholdController();
                    boolean correct = hcon.removeHousehold(householdList.get(r));
                    if(correct){
                        JOptionPane.showMessageDialog(this, "Xoá thành công!", "Thông báo", 1);
                    }
                    else{
                        JOptionPane.showMessageDialog(this, "Đã có lỗi xảy ra!", "Thông báo", 0);
                    }
                } catch (SQLException ex) {
                    Logger.getLogger(HouseholdManageJP.class.getName()).log(Level.SEVERE, null, ex);
                }
                showHousehold();
            }
        } else JOptionPane.showMessageDialog(jPanel1, "Chọn hàng để xóa!", "Thông báo", 0);
    }//GEN-LAST:event_deleteHouseHoldBtnActionPerformed

    private void addHouseHoldBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addHouseHoldBtnActionPerformed
        // TODO add your handling code here:
        new AddHouseholdJF().setVisible(true);
    }//GEN-LAST:event_addHouseHoldBtnActionPerformed

    private void seeHouseHoldBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seeHouseHoldBtnActionPerformed
        // TODO add your handling code here:
        int r = householdTable.getSelectedRow();
        if(r > -1){
            Household h = householdList.get(r);
            IndexView.jpnContent.removeAll();    
            IndexView.jpnContent.setLayout(new BorderLayout());
            IndexView.jpnContent.add(new InfoHouseholdJP(h));
            IndexView.jpnContent.validate();
            IndexView.jpnContent.repaint();
        } else JOptionPane.showMessageDialog(jPanel1, "Chọn hàng để xem!", "Thông báo", 0);
    }//GEN-LAST:event_seeHouseHoldBtnActionPerformed

    private void btnChangeInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChangeInfoActionPerformed
        // TODO add your handling code here:
        int r = householdTable.getSelectedRow();
        if(r > -1){
            new AdjustHouseholdJF(householdList.get(r)).setVisible(true);
        } else JOptionPane.showMessageDialog(jPanel1, "Chọn hàng để chỉnh sửa!", "Thông báo", 0);
        showHousehold();
    }//GEN-LAST:event_btnChangeInfoActionPerformed

    private void btnSearchHouseholdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchHouseholdActionPerformed
        try {
            // TODO add your handling code here:
            String s = txtName.getText();
            HouseholdController hcon = new HouseholdController();
            List<Household> result = hcon.findHousehold(s);
            model.setRowCount(0);
            for(Household h : result){
                model.addRow(new Object[]{model.getRowCount() + 1, 
                    h.getHouseholder(), h.getNumOfPeople()});
            }
        } catch (SQLException ex) {
            Logger.getLogger(HouseholdManageJP.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnSearchHouseholdActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addHouseHoldBtn;
    private javax.swing.JButton btnChangeInfo;
    private javax.swing.JButton btnSearchHousehold;
    private javax.swing.JButton deleteHouseHoldBtn;
    private javax.swing.JTable householdTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton seeHouseHoldBtn;
    private javax.swing.JTextField txtName;
    // End of variables declaration//GEN-END:variables
}
